### ISSUE TITLE
Intent to package: Snaps are universal Linux packages

### ISSUE THREAD

**Issue by brlin-tw** [Nixola/VRRTest#5]
Dear maintainer(s), 

[Snaps are universal Linux packages](https://snapcraft.io) that can be installed and run on supported GNU+Linux distributions with ease.  I've been following [the Snapcrafters protocols](https://github.com/snapcrafters/snap-repo-template#remaining-tasks) and [have built a working snap on the Snap Store](https://snapcraft.io/vrrtest), you may try it out by referring the instructions of the Snap Store listing page:
 
[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/vrrtest)

I'm also looking forward to working with you to make the packaging work upstream (if you're interested).  You may want to check out [the packaging recipe](https://gitlab.com/brlin/vrrtest-snap), [the documentation](https://docs.snapcraft.io), register a developer account on [the Snap Store](https://snapcraft.io/store), and get in touch to transfer the work under your control.

Thanks for your time and attention.

**Comment by Nixola** [comment]
Hi, I honestly don't want to have anything to do with snaps. I dislike the implementation and, on some level, the concept itself. You're free to maintain the snap packaging yourself if you so choose, but I have no intention of directly managing it, particularly because I don't use snapd.
However, do let me know if there's anything I can do to make it easier on your end.

**Comment by brlin-tw** [comment]
Understood.  In that case, I'll continue maintaining the snap distribution.  Feel free to notify me if there are any details of the distribution that need to be adjusted which I'll happily oblige.

Thanks!
